### ISSUE TITLE
README typos

### ISSUE THREAD

**Issue by bolinocroustibat** [src-r-r/python-stanza#1]
I think the README is referring to the standard `pyproject.toml` Python metadata file, not pypoetry.toml, right?

If yes, there are two typos:
- "Convert a pip-based project to to pypoetry.toml" -> "Convert a pip-based project to to pyproject.toml"
- "`Convert requirements.txt to pypoetry.toml`" -> "`Convert requirements.txt to pyproject.toml`"

**Comment by src-r-r** [comment]
Thanks. If I remember correctly I was needing to pee when making the README and committing it. I'll get it fixed. And take more bathroom breaks.

**Comment by src-r-r** [comment]
Closed in https://github.com/src-r-r/python-stanza/pull/4 and https://github.com/src-r-r/python-stanza/pull/3
